const { AppError } = require("../../errors/app-error");

const NEXT_FY_ERROR_CODES = Object.freeze({
  NEXT_FY_NOT_FOUND: "NEXT_FY_NOT_FOUND",
  NEXT_FY_INVALID_SOURCE_YEAR: "NEXT_FY_INVALID_SOURCE_YEAR",
  NEXT_FY_INVALID_TARGET_YEAR: "NEXT_FY_INVALID_TARGET_YEAR",
  NEXT_FY_YEAR_SEQUENCE_INVALID: "NEXT_FY_YEAR_SEQUENCE_INVALID",
  NEXT_FY_SOURCE_INELIGIBLE: "NEXT_FY_SOURCE_INELIGIBLE",
  NEXT_FY_MANUAL_BASELINE_DISABLED: "NEXT_FY_MANUAL_BASELINE_DISABLED",
  NEXT_FY_AMBIGUOUS_ASSUMPTION_RULE: "NEXT_FY_AMBIGUOUS_ASSUMPTION_RULE",
  NEXT_FY_VERSION_CONFLICT: "NEXT_FY_VERSION_CONFLICT",
  NEXT_FY_LINE_VERSION_CONFLICT: "NEXT_FY_LINE_VERSION_CONFLICT",
  NEXT_FY_NOT_EDITABLE: "NEXT_FY_NOT_EDITABLE",
  NEXT_FY_UNDER_REVIEW: "NEXT_FY_UNDER_REVIEW",
  NEXT_FY_ALREADY_APPROVED: "NEXT_FY_ALREADY_APPROVED",
  NEXT_FY_LOCKED: "NEXT_FY_LOCKED",
  NEXT_FY_REGENERATION_BLOCKED: "NEXT_FY_REGENERATION_BLOCKED",
  NEXT_FY_ADJUSTMENT_REASON_REQUIRED: "NEXT_FY_ADJUSTMENT_REASON_REQUIRED",
  NEXT_FY_DUPLICATE_GENERATION: "NEXT_FY_DUPLICATE_GENERATION",
  NEXT_FY_INVALID_AMOUNT: "NEXT_FY_INVALID_AMOUNT"
});

function nextFyError(statusCode, publicCode, publicMessage, details) {
  return new AppError({ statusCode, publicCode, publicMessage, details });
}

module.exports = {
  NEXT_FY_ERROR_CODES,
  nextFyError
};
