const { AppError } = require("../../errors/app-error");

const TRANSFER_ERROR_CODES = Object.freeze({
  TRANSFER_NOT_FOUND: "TRANSFER_NOT_FOUND",
  TRANSFER_INVALID_AMOUNT: "TRANSFER_INVALID_AMOUNT",
  TRANSFER_SOURCE_NOT_APPROVED: "TRANSFER_SOURCE_NOT_APPROVED",
  TRANSFER_DESTINATION_INVALID: "TRANSFER_DESTINATION_INVALID",
  TRANSFER_SOURCE_DESTINATION_SAME: "TRANSFER_SOURCE_DESTINATION_SAME",
  TRANSFER_INSUFFICIENT_BALANCE: "TRANSFER_INSUFFICIENT_BALANCE",
  TRANSFER_VERSION_CONFLICT: "TRANSFER_VERSION_CONFLICT",
  TRANSFER_NOT_EDITABLE: "TRANSFER_NOT_EDITABLE",
  TRANSFER_NOT_APPROVED: "TRANSFER_NOT_APPROVED",
  TRANSFER_ALREADY_POSTED: "TRANSFER_ALREADY_POSTED",
  TRANSFER_NOT_POSTED: "TRANSFER_NOT_POSTED",
  TRANSFER_POSTING_DISABLED: "TRANSFER_POSTING_DISABLED",
  TRANSFER_REVERSAL_DISABLED: "TRANSFER_REVERSAL_DISABLED",
  TRANSFER_DUPLICATE_REQUEST: "TRANSFER_DUPLICATE_REQUEST"
});

function transferError(statusCode, publicCode, publicMessage, details) {
  return new AppError({ statusCode, publicCode, publicMessage, details });
}

module.exports = {
  TRANSFER_ERROR_CODES,
  transferError
};
